---

- name: Lxc
  # depends on go, dnsmasq, squashfs
  packer: name={{ item }} state=present
  with_items: 
    - lxc
    - lxd
  service: name=lxd state=started
  # if Archlinux: compile kernel(?), log out and back in, configure networking
