---

https://wiki.archlinux.org/index.php/NFS

http://www.whaleblubber.ca/boot-raspberry-pi-nfs/

http://raspberrypi.stackexchange.com/questions/628/how-do-i-configure-the-raspberry-pi-to-boot-with-an-nfs-root
