 before_script: 
  - apt-get update -y -qq
  - apt-get install -y -qq python-dev libxml2-dev libxslt-dev python-pip python-apt git
  - echo "deb http://ftp.debian.org/debian jessie-backports main" >> /etc/apt/sources.list
  - apt-get update
  - apt-get install -qq -y -t jessie-backports ansible
 # - pip install git+git://github.com/ansible/ansible.git@devel
 
 ansible: 
  script:
    - ansible-playbook --syntax-check laptop.yml -i hosts
