before_script:
 - apt-get update -qq
 - apt-get install -y -qq python-dev libxml2-dev libxslt-dev easy_install vagrant
 - easy_install pip
 - pip install git+git://github.com/ansible/ansible.git@devel
 
vagr:
 script:
  - vagrant up
  
ansi:
 script:
  - ansible-playbook --syntax-check laptop.yml -i hosts --sudo-ask-pass --check
  
# Idempotence
#    - >
#     ansible-playbook -i inventory ansible/test.yml --connection=local
#     | grep -q 'changed=0.*failed=0'
#     && (echo 'Idempotence test: pass' && exit 0)
#     || (echo 'Idempotence test: fail' && exit 1)
