---

#- name: Clone dotfiles from public github repo
#  git: repo=https://github.com/liamesteban/dotfiles.git dest=/home/liam/.dotfiles # accept_hostkey=yes
#  become: true
#  become_user: liam

- name: Install dotfiles with dotbot
  # if dotfiles exists
  shell: chdir=/home/liam/.dotfiles bash ./install
