---

- name: Install packages to set up base environment
  become: yes
  pacman: name={{ item }} state=present
  with_items:
    - vim
    - tmux
    - zsh
    - lsof
    - htop
    - ranger
    - neovim
  when: ansible_os_family != "Debian"

- name: Install packages to set up base environment
  packer: name={{ item }} state=present
  with_items:
    - percol
    - fasd
  when: ansible_os_family != "Debian"
