---

- name: Install packages to set up base environment
  sudo: yes
  pacman: name="{{item}}" state=present
  with_items:
    - vim
    - tmux
    - zsh
    - lsof
    - htop
  when: ansible_os_family != "Debian"
