---

- name: Install packages to set up base environment
  sudo: yes
  apt: name="{{item}}" state=present
  with_items:
    - make
    - vim
    - git
    - tmux
    - zsh
  when: ansible_os_family == "Debian"
