- name: Install stuff from the aur
  packer: name={{ item }} state=present
  with_items:
    - redshift
    - ttf-roboto
    - arc-gtk-theme
    - arc-icon-theme
    - archdroid-icon-theme
    - fingerprint-gui
    - google-chrome
    - silversearcher-ag
    - filezilla
    - lemonbar
    - arbtt
    - gource
    - spotify
    - tomahawk-git
    - arandr
