---

- name: Add directory
  file: path=/etc/systemd/system/getty@tty1.service.d state=directory

- name: Add auto-login service files
  template: src=autologin.j2 dest=/etc/systemd/system/getty@tty1.service.d/autologin.conf

  # depends on dotfiles
  # unless already there
- name: Configure auto-login (dot profile)
  become: true
  become_user: liam
  blockinfile: 
    dest: /home/liam/.profile 
    create: yes 
    block: |
      if [ -z $DISPLAY ] && [ -n $XGD_VTNR ] && [ $XDG_VTNR -eq 1 ];then
        xinit awesome
      fi

- name: Enable auto-login service
  service: name=getty@tty1 enabled=yes
