- name: Install packages for x
  apt: name={{ item }} state=present
  with_items:
    - xserver-xorg-core
    - xmonad
    - xinit
    - xterm
    - dunst
    - filelight
    - mpv
    - scrot
    - xbacklight
  when: ansible_os_family == "Debian"

- name: Install packages for x
  pacman: name={{ item }} state=present
  with_items:
    - xorg
    - xmonad
    - xorg-xinit
    - xterm
    - dunst
    - feh
    - bspwm
    - sxhkd
    - nautilus
    - lxappearance
    - awesome
    - mpv
    - scrot
  when: ansible_os_family != "Debian"

- name: edit /etc/X11/Xwrapper.config
  blockinfile: 
    dest: /etc/X11/Xwrapper.config 
    create: yes
    block: |
      allowed_users=anybody
      needs_root_rights=yes
