---

- include: install.yml
- include: auto-login.yml
- include: fonts.yml
# order is important: audio, virtualbox
- include: audio.yml
  when: final_tests is defined
- include: virtualbox.yml
  when: final_tests is defined
- include: aur.yml
  when: ansible_os_family != "Debian"
