- name: Install packages for x
  apt: name={{ item }} state=present
  with_items:
    - xserver-xorg-core
    - xmonad
    - xinit
    - xterm
    - dunst
  when: ansible_os_family == "Debian"

- name: Install packages for x
  pacman: name={{ item }} state=present
  with_items:
    - xorg
    - xmonad
    - xorg-xinit
    - xterm
    - dunst
  when: ansible_os_family == "ArchLinux"
