---

# Installs deluge on a server. Should be trivial to modify for laptop/GUI too
# deluge web port is 8112
- name: Install deluge + web-ui
  apt: name="{{ item }}" state=present
  with_items:
    - deluge
    - deluged
    - deluge-web
  when: ansible_os_family == "Debian"

- name: Install deluge + web-ui
  pacman: name="{{ item }}" state=present
  with_items:
    - deluge
    - deluged
    - deluge-web
  when: ansible_os_family == "Arch Linux"

- name: Start, enable deluged systemd service
  service: name=deluged state=started enabled=yes

- name: Stop deluged
  service: name=deluged state=stopped

  # deluged must not be running (see above) 
  # 10 is for admin
- name: Add password to auth config file
  lineinfile: dest=/home/liam/.config/deluge/auth line="liam:password:10" state=present create=True

  # on line that matches allow_remote, replace false with true
- name: Allow remote
  # or inline
  lineinfile: 
    dest: /home/liam/.config/deluge/core.conf
    state: present 
    create: True
    regexp: 'allow_remote'
    line: '"allow_remote"\: true,'

- name: Copy deluge-web systemd service file
  copy: src=deluge-web.service dest=/etc/systemd/system/multi-user.target.wants

- name: Start, enable deluge-web systemd service
  service: name=deluge-web state=started enabled=yes

- name: Start deluged
  service: name=deluged state=started

# Configure more/my settings # probably from dotfiles

# http://dev.deluge-torrent.org/wiki/UserGuide/ThinClient
# template @ https://github.com/GR360RY/ansible-role-deluge/blob/master/templates/core.conf.j2
