---

# Installs deluge on a server. Should be trivial to modify for laptop/GUI too
# deluge web port is 8112
- name: Install deluge + web-ui
  apt: name="{{ item }}" state=present
  with_items:
    - deluge
    - deluged
    - deluge-web

- name: Install deluge
  apt: name=deluge state=installed

- name: Install deluge-web
  apt: name=deluge-web state=installed

- name: Start, enable deluged systemd service
  service: name=deluged state=started enabled=yes

- name: Stop deluged
  service: name=deluged state=stopped

  # deluged must not be running (see above) 
  # 10 is for admin
- name: Add password to auth config file
  lineinfile: dest=/home/liam/.config/deluge/auth line="liam:password:10" state=present create=True

  # on line that matches allow_remote, replace false with true
  #- name: Allow remote
  #  inline: "dest=/home/liam/.config/deluge/core.conf regexp='allow_remote' line='"allow_remote"\: true,' state=present create=True"

- name: Start, enable deluge-web systemd service
  service: name=deluge-web state=started enabled=yes

- name: Start deluged
  service: name=deluged state=started

# Configure more/my settings # probably from dotfiles

# http://dev.deluge-torrent.org/wiki/UserGuide/ThinClient
# template @ https://github.com/GR360RY/ansible-role-deluge/blob/master/templates/core.conf.j2
