- name: Install dependencies for Rofi
  apt: pkg={{ item }} update_cache=yes cache_valid_time=604800 install_recommends=no
  with_items:
    - autoconf
    - automake
    - pkg-config
    - libpango1.0-dev
    - libpangocairo-1.0-0
    - libcairo2-dev
    - libglib2.0-dev
    - libstartup-notification0-dev
    - libxcb-util0-dev
    - libxkbcommon-x11-dev
    - libxcb-ewmh-dev
    - libxcb-xinerama0-dev
    - libxcb-icccm4-dev
    - libxkbcommon
    - libxkbcommon-x11

xcb-ewmh xcb-icccm xcb-xrm xcb-randr xcb-xinerama
  sudo: yes

- name: Get Rofi source code
  git: repo=https://github.com/DaveDavenport/rofi.git accept_hostkey=True dest=/home/liam/sys/source/rofi/rofi
  register: rofi_checkout

- name: Install dependencies for building software from source
  apt: name=dh-autoreconf state=present

- name: autoreconf
  command: chdir=/home/liam/sys/source/rofi/rofi /usr/bin/autoreconf -i become=yes

- name: configure
  command: chdir=/home/liam/sys/source/rofi/rofi ./configure --prefix=/home/liam/.local/bin become=yes

- name: make
  make: chdir=/home/liam/sys/source/rofi/rofi

- name: make install
  make: chdir=/home/liam/sys/source/rofi/rofi target=install become=yes

  #- name: Install Rofi
  #  shell: cd ~/software/rofi && make distclean ; autoreconf -i && mkdir -p build && cd build && ../configure --prefix=$HOME/.local/ --disable-i3support && make && make install
  #  when: rofi_checkout|changed or rofi_installed.rc == 1
