---

- name: Install packages to set up base environment
  sudo: yes
  pacman: name="{{item}}" state=present
  with_items:
    - make
    - vim
    - git
    - tmux
    - zsh
    - lsof
    - percol
  when: ansible_os_family == "Arch Linux"
