---

- name: Set the hostname
  hostname: name={{ hostname }}

- name: Set the keyboard for the tty
  command: localectl set-keymap --no-convert uk
  become: yes
  when: ansible_os_family != "Debian"
  # /etc/vconsole.conf

- name: Generate locale
  locale_gen: name=en_GB.UTF-8 state=present
