---

- name: install sudo
  package: name=sudo state=installed

- name: "Make sure there's a 'wheel' group"
  group:
    name: wheel
    state: present

- name: Make user liam
  user: name=liam password="pass.enact" groups=wheel append=yes state=present createhome=yes

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'

- name: Edit /etc/hosts for sudo hostname
  lineinfile: dest=/etc/hosts insertafter='127.0.0.1' line='127.0.1.1   laptop'
