---

- name: install sudo
  apt:  name=sudo
        state=installed

- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Add sudoers users to wheel group
  user: name=liam password="pass.enact" groups=wheel append=yes state=present createhome=yes

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
