---

- name: Install the necessary programs
pacman: name={{ item }} state=present
with_items:
    - wpa_supplicant
    - wpa_actiond
    - ifplugd
    - crda
    - dialog

- name: Enable the services
service: name={{ item }} state=started enabled=yes
with_items: 
    - netctl-auto
    - netctl-ifplugd

- name: 'Copy wpa supplicant file'
  copy: src=./wpa_supplicant.conf dest=/etc/wpa_supplicant/wpa_supplicant.conf mode=0600
