---

- name: Install required packages
  pacman: name={{ item }} state=present
  with_items:
    - avahi
    - nss-mdns

- name: Appends mdns to the hosts line in /etc/nsswitch.conf

- name: Enable the services
  service: name=avahi-daemon enabled=yes
